### ISSUE TITLE
Adolfo ElixirConfBR talk -> resources (stickers)

### ISSUE THREAD

**Issue by pdgonzalez872** [erlef/education-wg#13]
@adolfont

Content: get slides from Code BEAM

**Comment by adolfont** [comment]
I submitted a talk to Elixir Brasil 2020 https://www.sympla.com.br/elixir-brasil-2020__736536
and it is about the Erlang Ecosystem Foundation.
Even if it is not accepted, I will attend the event.
@miriampena suggested I take some stickers with me.

**Comment by pdgonzalez872** [comment]
Closing this for now
