### ISSUE TITLE
Update Member List on the main website

### ISSUE THREAD

**Issue by elbrujohalcon** [erlef/education-wg#24]
Go [here](https://github.com/erlef/website/blob/master/priv/working_groups/education.md) and submit a PR to update the list of members in [this page](https://erlef.org/wg/education)

**Comment by ericdouglas** [comment]
@elbrujohalcon I can do this but who will be added?

The file to be updated is [this one](https://github.com/erlef/website/blob/master/lib/erlef_web/templates/page/education.html.eex) I believe.
